/* Copyright © SixtyFPS GmbH <info@slint-ui.com>
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

import {
    ComboBox, VerticalBox, HorizontalBox, GridBox, Button,
    LineEdit, ListView, GroupBox, CheckBox, TabWidget,
    AboutSlint
} from "std-widgets.slint";

import {
    Action, Feature, CargoView, Diag, DependencyData, DependencyNode, BuildingPane
} from "cargo.slint";

import { Toolchain, RustupView } from "rustup.slint";
import { CargoInstallView, InstalledCrate, CargoInstallData } from "install.slint";
import { CratesCompletionData } from "crates_completion.slint";
export {DependencyData, DependencyNode, CargoInstallData, CratesCompletionData }

export component CargoUI inherits Window {
    title: "Cargo UI";
    icon: @image-url("rust-logo.png");
    preferred_height: 550px;
    preferred_width: 500px;

    in-out property <string> cargo-ui-version: "x.y.z";
    callback open-url(string);

    // Cargo aliases
    in-out property status <=> cargo-view.status;
    in-out property packages <=> cargo-view.packages;
    in-out property allow-package_selection <=> cargo-view.allow_package-selection;
    in-out property current-package <=> cargo-view.current-package;
    in-out property extra-run <=> cargo-view.extra-run;
    in-out property extra-test <=> cargo-view.extra-test;
    callback action <=> cargo-view.action;
    callback cancel <=> cargo-view.cancel;
    in-out property is-building <=> cargo-view.is-building;
    in-out property diagnostics <=> cargo-view.diagnostics;
    in-out property workspace-valid <=> cargo-view.workspace-valid;
    in-out property manifest-path <=> cargo-view.manifest-path;
    in-out property build-results <=> cargo-view.build-results;
    in-out property check-results <=> cargo-view.check-results;
    callback reload-manifest <=> cargo-view.reload-manifest;
    callback show-open-dialog <=> cargo-view.show-open-dialog;
    in-out property build-pane-visible <=> cargo-view.build-pane-visible;
    in-out property has-features <=> cargo-view.has-features;
    in-out property package-features <=> cargo-view.package-features;
    in-out property enable-default-features <=> cargo-view.enable-default-features;
    callback package-selected <=> cargo-view.package-selected;

    // Rustup aliases
    in-out property toolchains <=> rustup-view.toolchains;
    in-out property toolchains-available <=> rustup-view.toolchains-available;

    VerticalBox {
        TabWidget {
            // hide the widgets from the tab focus handler when covered:
            visible: !(root.is-building || root.build-pane-visible);

            Tab {
                title: "Project / Workspace";
                cargo-view := CargoView {
                    background: root.background;
                }
            }

            Tab {
                title: "Install";
                CargoInstallView { }
            }

            Tab {
                title: "Toolchains";
                rustup-view := RustupView {
                    width: 100%;
                    height: 100%;
                }
            }

            Tab {
                title: "About";
                VerticalBox {
                    Text {
                        text: "Cargo UI \{root.cargo-ui-version}";
                        font-size: 40px;
                    }
                    Text {
                        text: "https://github.com/slint-ui/cargo-ui";
                        color: blue;
                        TouchArea { clicked => { root.open-url(parent.text); } }
                    }
                    Text {
                        text: "License: GNU General Public License Version 3";
                        TouchArea { clicked => { root.open-url("https://github.com/slint-ui/cargo-ui/blob/master/LICENSE-GPL"); } }
                    }

                    Rectangle {}

                    HorizontalBox {
                        alignment: end;
                        vertical-stretch: 0;
                        TouchArea {
                            clicked => { root.open-url("https://slint-ui.com"); }
                            VerticalLayout {
                                AboutSlint {  }
                            }
                        }
                    }
                }
            }
        }
    }

    animated := Rectangle {
        width: 100%; height: 100%;
        y: parent.height;
        states [
            visible when (root.is_building || root.build_pane_visible) : {
                y: 0;
            in  {
                animate y { duration: 200ms; easing: ease; }
            }
            out  {
                animate y { duration: 200ms; easing: ease; }
            }
            }
        ]

        if (animated.y < root.height): BuildingPane {
            background: root.background;
            status: root.status;
            diagnostics: root.diagnostics;
            cancel => { root.cancel() }
            back => { root.build_pane_visible = false; }
            is_building: root.is_building;
        }
    }
}
