/* Copyright © SixtyFPS GmbH <info@slint-ui.com>
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

 import { GroupBox, VerticalBox } from "std-widgets.slint";


export struct Toolchain := {
    name: string,
    default: bool
}

export RustupView := GroupBox {
    title: "Installed Toolchains";

    property<[Toolchain]> toolchains;
    property<bool> toolchains-available: false;

    VerticalBox { 
        if toolchains-available: VerticalLayout {
            alignment: start;

            for toolchain in toolchains: Text {
                text: toolchain.name;
                font-weight: toolchain.default ? 800 : 400;
            }
        }
        if !toolchains-available: Text {
            text: "Refreshing toolchains - please wait";
            vertical-alignment: center;
        }
    }
}
