/* Copyright © SixtyFPS GmbH <info@slint-ui.com>
 * SPDX-License-Identifier: MIT OR Apache-2.0
 */

 import { GroupBox, VerticalBox } from "std-widgets.slint";


export struct Toolchain  {
    name: string,
    default: bool
}

export component RustupView inherits GroupBox {
    title: "Installed Toolchains";

    in-out property<[Toolchain]> toolchains;
    in-out property<bool> toolchains-available: false;

    VerticalBox { 
        if root.toolchains-available: VerticalLayout {
            alignment: start;

            for toolchain in root.toolchains: Text {
                text: toolchain.name;
                font-weight: toolchain.default ? 800 : 400;
            }
        }
        if !root.toolchains-available: Text {
            text: "Refreshing toolchains - please wait";
            vertical-alignment: center;
        }
    }
}
